/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 17: module: command not found
/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 20: module: command not found
Traceback (most recent call last):
  File "/cluster/home/eglimar/inf-extr/scripts/ms-diag/llama2-chat/zero_shot.py", line 269, in <module>
    main()
  File "/cluster/home/eglimar/inf-extr/scripts/ms-diag/llama2-chat/zero_shot.py", line 221, in main
    df = load_data()
  File "/cluster/home/eglimar/inf-extr/scripts/ms-diag/llama2-chat/zero_shot.py", line 145, in load_data
    df = load_dataset(os.path.join(paths.DATA_PATH_PREPROCESSED,'ms-diag'), data_files = data_files)
  File "/cluster/customapps/biomed/grlab/users/eglimar/conda/envs/inf-extr/lib/python3.9/site-packages/datasets/load.py", line 2110, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/cluster/customapps/biomed/grlab/users/eglimar/conda/envs/inf-extr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/cluster/customapps/biomed/grlab/users/eglimar/conda/envs/inf-extr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/cluster/dataset/midatams/inf-extr/data/preprocessed/ms-diag/state.json'
